language: csharp
solution: PikeMQ.sln
install:
  - nuget restore PikeMQ.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release PikeMQ.sln
after_script:
  - nunit-console ./PikeMQ.Server.Test/bin/Release/netcoreapp1.1/PikeMQ.Server.Test.dll
  - nunit-console ./Tests/bin/Release/netcoreapp1.1/PikeMQ.Core.Test.dll
  - nunit-console ./PikeMQ.Client.Test/bin/Release/netcoreapp1.1/PikeMQ.Client.Test.dll
